# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "quiz"
client_id = "71d081088eaaf10e3b3a4d2b6155aad8"
application_url = "https://dedicated-consistency-draws-effectively.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dedicated-consistency-draws-effectively.trycloudflare.com/auth/callback",
  "https://dedicated-consistency-draws-effectively.trycloudflare.com/auth/shopify/callback",
  "https://dedicated-consistency-draws-effectively.trycloudflare.com/api/auth/callback",
  "https://dedicated-consistency-draws-effectively.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demomywork.myshopify.com"
